# Generated by Django 5.2.7 on 2025-10-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student User'), ('staff', 'Staff User'), ('admin', 'Administrator User')], default='student', max_length=50),
        ),
    ]
