# Generated by Django 5.2.7 on 2025-10-20 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LendingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('status', models.CharField(choices=[('new', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('issued', 'Issued'), ('overdue', 'Overdue')], default='new', max_length=100)),
                ('requested_date', models.DateField()),
                ('issued_date', models.DateField()),
                ('returned_date', models.DateField()),
            ],
        ),
    ]
