# Generated by Django 5.2.7 on 2025-10-20 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('lending', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingrequest',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lendingrequest',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requested_item', to='equipment.item'),
        ),
        migrations.AddField(
            model_name='lendingrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requested_lending', to=settings.AUTH_USER_MODEL),
        ),
    ]
