# Generated by Django 5.2.7 on 2025-11-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingrequest',
            name='purpose',
            field=models.CharField(choices=[('new', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('issued', 'Issued'), ('returned', 'Returned')], default='new', max_length=1000),
        ),
        migrations.AlterField(
            model_name='lendingrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('issued', 'Issued'), ('returned', 'Returned')], default='new', max_length=100),
        ),
    ]
