# Generated by Django 5.2.7 on 2025-11-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0003_lendingrequest_purpose_alter_lendingrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingrequest',
            name='issued_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='lendingrequest',
            name='returned_date',
            field=models.DateField(null=True),
        ),
    ]
