# Generated by Django 5.2.7 on 2025-11-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0004_alter_lendingrequest_issued_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingrequest',
            name='purpose',
            field=models.CharField(default='new', max_length=1000),
        ),
    ]
