# Generated by Django 5.2.7 on 2025-10-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('sports', 'Sports Kits'), ('lab', 'Lab Equipment'), ('cameras', 'Cameras'), ('muscial', 'Musical Instruments'), ('project', 'Project Materials')], max_length=100)),
                ('condition', models.CharField(choices=[('working', 'Working'), ('broken', 'Needs repair')], default='Working', max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('availability', models.IntegerField(default=0)),
            ],
        ),
    ]
