# Generated by Django 5.2.7 on 2025-10-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports Kits'), ('lab', 'Lab Equipment'), ('cameras', 'Cameras'), ('musical', 'Musical Instruments'), ('project', 'Project Materials')], max_length=100),
        ),
    ]
