# Generated by Django 5.2.7 on 2025-10-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('New', 'Brand New'), ('Good', 'Not new but good'), ('Fair', 'Okay to work with'), ('Broken', 'not in working condition')], default='Working', max_length=100),
        ),
    ]
