# Generated by Django 5.2.7 on 2025-10-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_alter_item_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('New', 'Brand New'), ('Good', 'Not new but good'), ('Fair', 'Okay to work with'), ('Broken', 'not in working condition')], default='New', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_item_name_category'),
        ),
    ]
