# Generated by Django 5.2.7 on 2025-10-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_item_condition_item_unique_item_name_category'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_item_name_category',
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('name', 'category', 'condition'), name='unique_item_name_category_condition'),
        ),
    ]
